add wave -position end  sim:/hyperbus_tb/axi_i/aw_id
add wave -position end  sim:/hyperbus_tb/axi_i/aw_addr
add wave -position end  sim:/hyperbus_tb/axi_i/aw_len
add wave -position end  sim:/hyperbus_tb/axi_i/aw_size
add wave -position end  sim:/hyperbus_tb/axi_i/aw_burst
add wave -position end  sim:/hyperbus_tb/axi_i/aw_lock
add wave -position end  sim:/hyperbus_tb/axi_i/aw_cache
add wave -position end  sim:/hyperbus_tb/axi_i/aw_prot
add wave -position end  sim:/hyperbus_tb/axi_i/aw_qos
add wave -position end  sim:/hyperbus_tb/axi_i/aw_region
add wave -position end  sim:/hyperbus_tb/axi_i/aw_user
add wave -position end  sim:/hyperbus_tb/axi_i/aw_valid
add wave -position end  sim:/hyperbus_tb/axi_i/aw_ready
add wave -position end  sim:/hyperbus_tb/axi_i/w_data
add wave -position end  sim:/hyperbus_tb/axi_i/w_strb
add wave -position end  sim:/hyperbus_tb/axi_i/w_last
add wave -position end  sim:/hyperbus_tb/axi_i/w_user
add wave -position end  sim:/hyperbus_tb/axi_i/w_valid
add wave -position end  sim:/hyperbus_tb/axi_i/w_ready
add wave -position end  sim:/hyperbus_tb/axi_i/b_id
add wave -position end  sim:/hyperbus_tb/axi_i/b_resp
add wave -position end  sim:/hyperbus_tb/axi_i/b_user
add wave -position end  sim:/hyperbus_tb/axi_i/b_valid
add wave -position end  sim:/hyperbus_tb/axi_i/b_ready
add wave -position end  sim:/hyperbus_tb/axi_i/ar_id
add wave -position end  sim:/hyperbus_tb/axi_i/ar_addr
add wave -position end  sim:/hyperbus_tb/axi_i/ar_len
add wave -position end  sim:/hyperbus_tb/axi_i/ar_size
add wave -position end  sim:/hyperbus_tb/axi_i/ar_burst
add wave -position end  sim:/hyperbus_tb/axi_i/ar_lock
add wave -position end  sim:/hyperbus_tb/axi_i/ar_cache
add wave -position end  sim:/hyperbus_tb/axi_i/ar_prot
add wave -position end  sim:/hyperbus_tb/axi_i/ar_qos
add wave -position end  sim:/hyperbus_tb/axi_i/ar_region
add wave -position end  sim:/hyperbus_tb/axi_i/ar_user
add wave -position end  sim:/hyperbus_tb/axi_i/ar_valid
add wave -position end  sim:/hyperbus_tb/axi_i/ar_ready
add wave -position end  sim:/hyperbus_tb/axi_i/r_id
add wave -position end  sim:/hyperbus_tb/axi_i/r_data
add wave -position end  sim:/hyperbus_tb/axi_i/r_resp
add wave -position end  sim:/hyperbus_tb/axi_i/r_last
add wave -position end  sim:/hyperbus_tb/axi_i/r_user
add wave -position end  sim:/hyperbus_tb/axi_i/r_valid
add wave -position end  sim:/hyperbus_tb/axi_i/r_ready
add wave -position end  sim:/hyperbus_tb/dut_i/axi2phy_i/hyper_axi_state
add wave -position end  sim:/hyperbus_tb/dut_i/phy_i/hyper_trans_state
